### ISSUE TITLE
Alternate of globalising variables.

### ISSUE THREAD

**Issue by ShubhamVG** [Dana-f559/Su-do-cuuuu#5]
Instead of making variables global, just pass them through the function. If the variable is a list, then any changes the function makes on the list is directly reflected on the list and hence "globalising" the variable is not needed. (Remember pointers)
For other type of variables like int and string, just make the function taking the input return the int or string (if any changes get made while running the function) or just return the int/string as it was.

**Comment by ShubhamVG** [comment]
Also, don't make "status" a global variable. The commented lines on the `run_game` function are eggsactly how the GUI should function. Actually, make the `status` a scoped variable (meaning a variable only accessible inside the `run_game` function and not outside it). `status` is nowhere needed apart from the `run_game` function.

**Comment by ShubhamVG** [comment]
And don't load the font every time inside the `insert` function.
Declare `myfont` right underneath the imports or the `pygame.init()` function.
```py
myfont = pygame.font.Font(f"{a}/fonts/comic-sans/comicsans.ttf", 35)
```

**Comment by Dana-f559** [comment]
done
